<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2015  Stephan Kreutzer

This file is part of mobileread_wiki_ebook_list_validator1.

mobileread_wiki_ebook_list_validator1 is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License version 3 or any later version,
as published by the Free Software Foundation.

mobileread_wiki_ebook_list_validator1 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License 3 for more details.

You should have received a copy of the GNU Affero General Public License 3
along with mobileread_wiki_ebook_list_validator1. If not, see <http://www.gnu.org/licenses/>.
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xhtml="http://www.w3.org/1999/xhtml" exclude-result-prefixes="xhtml">
  <xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes"/>

  <xsl:template match="/xhtml:html">
    <mobileread-thread-attachment-link>
      <xsl:comment> This file was generated by mobileread_thread_page.xsl of mobileread_wiki_ebook_list_validator1, which is free software licensed under the GNU Affero General Public License 3 or any later version (see https://github.com/publishing-systems/clients/ and http://www.publishing-systems.org). </xsl:comment><xsl:text>&#xA;</xsl:text>
      <xsl:apply-templates/>
    </mobileread-thread-attachment-link>
  </xsl:template>

  <xsl:template match="/xhtml:html/xhtml:body/xhtml:div[@id='container']/xhtml:div[@id='posts']/xhtml:div/xhtml:div/xhtml:div/xhtml:div/xhtml:table/xhtml:tr/xhtml:td/xhtml:div/xhtml:fieldset/xhtml:table/xhtml:tr/xhtml:td/xhtml:a">
    <link>
      <xsl:attribute name="name">
        <xsl:value-of select="./text()"/>
      </xsl:attribute>
      <xsl:text>http://www.mobileread.com/forums/</xsl:text>
      <xsl:value-of select="./@href"/>
    </link>
  </xsl:template>

  <xsl:template match="/xhtml:html/xhtml:body/xhtml:div[@id='container']/xhtml:div[@id='posts']/xhtml:div/xhtml:div/xhtml:div/xhtml:div/xhtml:table/xhtml:tr/xhtml:td/xhtml:div/xhtml:a">
    <xsl:variable name="attachmentlink" select="@href"/>
    <xsl:if test="starts-with($attachmentlink, 'http://www.mobileread.com/forums/attachment.php?')">
      <link>
        <xsl:attribute name="name">
          <xsl:value-of select="./text()"/>
        </xsl:attribute>
        <xsl:value-of select="./@href"/>
      </link>
    </xsl:if>
  </xsl:template>

  <xsl:template match="/xhtml:html/xhtml:body/xhtml:div[@id='container']/xhtml:div[@id='posts']/xhtml:div/xhtml:div/xhtml:div/xhtml:div/xhtml:table/xhtml:tr/xhtml:td/xhtml:div/xhtml:a[@class='bigusername']">
    <user link="{@href}" post="{./../@id}">
      <xsl:value-of select=".//text()"/>
    </user>
  </xsl:template>

  <xsl:template match="text()|@*"/>

</xsl:stylesheet>
