# Copyright (C) 2015  Stephan Kreutzer
#
# This file is part of clients for automated_digital_publishing.
#
# clients for automated_digital_publishing is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3 or any later version,
# as published by the Free Software Foundation.
#
# clients for automated_digital_publishing is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License 3 for more details.
#
# You should have received a copy of the GNU Affero General Public License 3
# along with clients for automated_digital_publishing. If not, see <http://www.gnu.org/licenses/>.



.PHONY: all setup1 clean



all: setup1
setup1: setup1.class



setup1.class: setup1.java
	javac setup1.java

clean:
	rm -f setup1.class

