# Copyright (C) 2016-2017  Stephan Kreutzer
#
# This file is part of clients for the automated_digital_publishing
# and digital_publishing_workflow_tools packages.
#
# clients is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3 or any later version,
# as published by the Free Software Foundation.
#
# clients is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License 3 for more details.
#
# You should have received a copy of the GNU Affero General Public License 3
# along with clients. If not, see <http://www.gnu.org/licenses/>.



directories = ./twitch_video_uploader_1



.PHONY: all $(directories)



all: $(directories)



$(directories):
	$(MAKE) --directory=$@

