<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2015  Stephan Kreutzer

This file is part of mobileread_wiki_ebook_list_validator1.

mobileread_wiki_ebook_list_validator1 is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License version 3 or any later version,
as published by the Free Software Foundation.

mobileread_wiki_ebook_list_validator1 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License 3 for more details.

You should have received a copy of the GNU Affero General Public License 3
along with mobileread_wiki_ebook_list_validator1. If not, see <http://www.gnu.org/licenses/>.
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes"/>

  <xsl:template match="/html">
    <mobileread-wiki-ebook-list>
      <xsl:comment> This file was generated by mobileread_wiki_ebook_list.xsl of mobileread_wiki_ebook_list_validator1, which is free software licensed under the GNU Affero General Public License 3 or any later version (see https://github.com/publishing-systems/clients/ and http://www.publishing-systems.org). </xsl:comment><xsl:text>&#xA;</xsl:text>
      <xsl:apply-templates/>
    </mobileread-wiki-ebook-list>
  </xsl:template>

  <xsl:template match="/html/body/div[@id='content']/div[@id='bodyContent']/div[@id='mw-content-text']/table/tr/td">
    <xsl:if test="./a[@class='external text'] and ./a/text() = 'ePub'">
      <link>
        <xsl:value-of select="./a/@href"/>
      </link>
    </xsl:if>
  </xsl:template>

  <xsl:template match="text()|@*"/>

</xsl:stylesheet>
